### PR TITLE
Update Footer.vue

### PR DESCRIPTION
**Pull request by junqili259**
Added linked footers to Binger

### CODE REVIEW

**Comment by ShinValor** [comment]
Can you provide a screenshot of the new footer
@junqili259

**Comment by junqili259** [comment]
> Can you provide a screenshot of the new footer
> @junqili259
image

**Comment by junqili259** [comment]
> Can you provide a screenshot of the new footer
> @junqili259
image

**Comment by ShinValor** [comment]
Why is it so tiny now lol

**Comment by junqili259** [comment]
> Why is it so tiny now lol

Might be my screen resolution as its 2560 x 1440

**Comment by ShinValor** [comment]
> > Why is it so tiny now lol
> 
> Might be my screen resolution as its 2560 x 1440

Can we keep it with 5 columns and just replace it with text

**Comment by junqili259** [comment]
> > > Why is it so tiny now lol
> > 
> > 
> > Might be my screen resolution as its 2560 x 1440
> 
> Can we keep it with 5 columns and just replace it with text

wdym replace it with text?

**Comment by ShinValor** [comment]
Like how u did it currently but with 5 column

**Comment by junqili259** [comment]
> Like how u did it currently but with 5 column

i think 3 columns is good enough since we don't have a lot of things to add

**Comment by junqili259** [comment]
@ShinValor What's the site you got the icons from?

**Comment by ShinValor** [comment]
> @ShinValor What's the site you got the icons from?

Ant Design https://www.antdv.com/components/icon/

**Comment by junqili259** [comment]
image
@ShinValor updated footers.

**Pull request merged**
