### PR TITLE
Installed Flickity

### PR DESCRIPTION
**Pull request by ShinValor**
Installed Vue Flickity and added a slider in Home

https://www.npmjs.com/package/vue-flickity

Screen Shot 2020-06-28 at 9 18 49 PM

### CODE REVIEW

**Comment by LeKinchi** [comment]
Why do we have this ?

**Comment by ShinValor** [comment]
> Why do we have this ?

To display movies as recommendation. This is different from the swiper fyi.

**Comment by LeKinchi** [comment]
> > Why do we have this ?
> 
> To display movies as recommendation. This is different from the swiper fyi.

On the Landing page ?

**Comment by ShinValor** [comment]
> > > Why do we have this ?
> > 
> > 
> > To display movies as recommendation. This is different from the swiper fyi.
> 
> On the Landing page ?

Possibly. Not sure yet. I put it on landing page for testing.

**Comment by LeKinchi** [comment]
Ok. I'll accept it for now then

**Pull request merged**
