### PR TITLE
Update routes.py

### PR DESCRIPTION
**Pull request by junqili259**
Commented out the key.json call from firebase in attempt to fix flask deployment bug.

### CODE REVIEW

**Comment by ShinValor** [comment]
@junqili259 Is there a reason to use port 50001

**Comment by junqili259** [comment]
> @junqili259 Is there a reason to use port 50001
I don't believe so.

**Comment by ShinValor** [comment]
> > @junqili259 Is there a reason to use port 50001
> > I don't believe so.

can u change back to 5000 and test if it still works.

**Comment by junqili259** [comment]
> > > @junqili259 Is there a reason to use port 50001
> > > I don't believe so.
> 
> can u change back to 5000 and test if it still works.

It works on my test env

**Pull request merged**
