### PR TITLE
added flask boilerplate

### PR DESCRIPTION
**Pull request by junqili259**

### CODE REVIEW

**Comment by junqili259** [comment]
> Can you name it to server/ instead of flask/?
> 
> Also provide some screenshot of the running flask server if possible.

sure i can change it to server and provide screenshot.

**Comment by ShinValor** [comment]
> > Can you name it to server/ instead of flask/?
> > Also provide some screenshot of the running flask server if possible.
> 
> sure i can change it to server and provide screenshot.

Sorry, I updated the comment. Naming api/ would be more fitting

**Comment by junqili259** [comment]
> > > Can you name it to server/ instead of flask/?
> > > Also provide some screenshot of the running flask server if possible.
> > 
> > 
> > sure i can change it to server and provide screenshot.
> 
> Sorry, I updated the comment. Naming api/ would be more fitting.

I've also added screenshots. Are those shots ok?

**Comment by ShinValor** [comment]
> > > > Can you name it to server/ instead of flask/?
> > > > Also provide some screenshot of the running flask server if possible.
> > > 
> > > 
> > > sure i can change it to server and provide screenshot.
> > 
> > 
> > Sorry, I updated the comment. Naming api/ would be more fitting.
> 
> I've also added screenshots. Are those shots ok?

Lmao. I bet putting screenshots in the PR comments, not in the repository.

**Comment by junqili259** [comment]
> Paste the screenshots in the PR's comment, not in the repository

flaskrun
success

here you go

**Pull request merged**
